services:
  app:
    build:
      context: .
    container_name: studi-voyage
    ports:
      - "8085:80"  # Accéder à l'application via localhost:8085
    env_file:
      - .env       # Charger les variables d'environnement
    depends_on:
      - db
    volumes:
      - .:/var/www/html  # Montre le dossier local dans le conteneur
    networks:
      - app-network


  db:
    image: mariadb:10.11
    container_name: studi-voyage-sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
